### ISSUE TITLE
大神好

### ISSUE THREAD

**Issue by CHAN-ui** [LvDunn/sephora_goods_alarm#1]
大神好，为啥我选择微信提醒然后发现三个问题.
1.微信网页版登陆不上
2.有货的商品显示现在无货，30秒后重新监控
3.登陆了PC端的微信没有提醒。
劳烦大神解惑！

**Comment by LyuDun** [comment]
抱歉很晚回复：
1. 微信逐渐限制了网页登陆，大部分人的微信都无法使用网页接口登陆了，新注册的更不能使用了。
2. 我会近期做更新，尝试增加qq或邮件提醒
3. 近期会修复商品的问题
4. shephora中国官网和美网不同，我的是适配的美网。
5. 丝芙兰美网的需要配合vpn使用，不然自动跳转到中国官网。

**Comment by CHAN-ui** [comment]
好的.等待更新.感谢！
